4-Nuga/goods-goods-duck-front

- src/app/api/auth/[...nextauth]/options.ts
> Fix: Auth 데이터 형식 변경

- .dockerignore
- .eslintrc.json
- .gitignore
- Dockerfile
- src/app/(member)/login/page.tsx
- src/containers/(member)/join/JoinForm.tsx
- src/containers/mypage/InfoArea.tsx
- src/containers/search/SearchModal.tsx
- src/containers/search/SearchVisible.tsx
- tsconfig.json
> #30 
> tsconfig.json 경로 수정 반영
> Fix:  tsconfig 경로 설정 변경

- src/containers/main/SoonAndHitsItem.tsx
- src/containers/notification/NotificationContent.tsx
- src/containers/notification/NotificationModal.tsx
- src/containers/notification/NotificationVisible.tsx
- src/dummydata/notification.json
- src/types/NotificationType.ts
> #16 
> 알림 화면 퍼블리싱
> svg 경로 수정 누락된 부분 반영
> Design: 알림 화면 퍼블리싱

- src/app/(goods)/registration/page.tsx
- src/components/Btn/BackBtn.tsx
- src/components/layout/RegistrationBtn.tsx
- src/containers/goods/registration/CategoryArea.tsx
- src/containers/goods/registration/DescriptionArea.tsx
- src/containers/goods/registration/DurationModal.tsx
- src/containers/goods/registration/GoodsForm.tsx
- src/containers/goods/registration/ImageArea.tsx
- src/containers/goods/registration/PeriodArea.tsx
- src/containers/goods/registration/RegistrationHeader.tsx
- src/containers/goods/registration/TagArea.tsx
- src/containers/goods/registration/TimeModal.tsx
- src/containers/goods/registration/TradeTypeArea.tsx
- src/containers/goods/registration/WeekModal.tsx
- src/containers/goods/registration/store.ts
> #34
> 상품 등록 퍼블리싱, 이미지 등록 기능 구현
> Feat: 상품 등록 퍼블리싱, 이미지 등록 기능 구현

- src/app/complain/page.tsx
- src/containers/complain/CheckList.tsx
- src/containers/complain/ComplainForm.tsx
- src/containers/complain/ComplainHeader.tsx
- src/containers/complain/ReasonArea.tsx
> Design: 신고 화면 퍼블리싱

- src/app/(goods)/seller/page.tsx
- src/containers/goods/seller/SellerHeader.tsx
- src/containers/goods/seller/SellerMannerDuck.tsx
- src/containers/goods/seller/SellerProfile.tsx
- src/containers/goods/seller/SellerReview.tsx
- src/dummydata/sellerReview.json
> Design: 판매자 정보 화면 퍼블리싱

- .vscode/settings.json
- public/svgs/icon/checkFalse.svg
- public/svgs/icon/checkTrue.svg
- src/app/(goods)/goods/layout.tsx
- src/app/(goods)/goods/page.tsx
- src/components/layout/Nav.tsx
- src/containers/goods/list/GoodsItem.tsx
- src/containers/goods/list/GoodsList.tsx
- src/containers/goods/registration/GoodsForm.tsx
- src/containers/goods/registration/TagArea.tsx
- src/containers/goods/seller/SellerReview.tsx
- src/dummydata/goodsItem.json
- src/dummydata/goodsList.json
- src/types/goodsType.ts
> #51 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 중간에 seller, registration 관련해서 수정된 부분은 지난 코드 리뷰 때 변경했던 내용입니다 ~
> Design: 굿즈 전체 조회 화면 퍼블리싱

- src/app/api/auth/[...nextauth]/options.ts
- src/containers/member/join/EasyForm.tsx
- src/containers/member/join/FullForm.tsx
- src/containers/member/join/NicknameInput.tsx
- src/containers/member/join/PhoneVerification.tsx
- src/containers/member/login/LoginForm.tsx
- src/utils/authApiActions.ts
> close #71 
> 소셜 매핑
> 소셜 로그인 시 간편회원가입 폼
> 로그인 에러 핸들링
> Feat: 소셜 로그인 관련 로직

- src/containers/member/join/EasyForm.tsx
- src/containers/member/join/FullForm.tsx
- src/containers/member/join/JoinFormArea.tsx
> Fix: 회원가입 모달

- public/sw.js
- src/containers/main/MainCategory.tsx
> Fix: 빌드 에러 해결

- src/app/api/auth/[...nextauth]/options.ts
- src/containers/mypage/update-password/ChangePasswordForm.tsx
- src/containers/mypage/update-profile/UpdateFavCategory.tsx
- src/containers/mypage/update-profile/UpdateNickname.tsx
- src/containers/mypage/update-profile/UpdateProfileForm.tsx
- src/containers/mypage/update-profile/store.ts
- src/utils/memberApiActions.ts
> Feat: 마이페이지 데이터

- src/app/mypage/update-password/page.tsx
- src/containers/mypage/update-password/ChangePasswordForm.tsx
- src/containers/mypage/update-password/NewPwdInput.tsx
- src/containers/mypage/update-password/NewPwdInput2.tsx
- src/containers/mypage/update-password/PwdInput.tsx
- src/containers/mypage/update-profile/UpdateProfileForm.tsx
- src/containers/mypage/update-profile/UpdateProfileImage.tsx
- src/middleware.ts
> Fix: 프로필 에러 수정

- src/app/duck-point/charge/page.tsx
- src/containers/duck-point/PointChargeForm.tsx
- src/containers/mypage/DuckPointArea.tsx
- src/types/memberApiDataType.ts
- src/utils/memberApiActions.ts
> Feat: 결제 시스템 테스트 연결

- src/containers/duck-point/DetailContent.tsx
- src/containers/mypage/MannerDuckArea.tsx
- src/utils/memberApiActions.ts
> #55 
> 마이페이지 매너덕 이미지 적용
> 덕포인트 사용내역 조회 확인
> Feat: 마이페이지 매너덕 조회 및 덕포인트 사용 내역 조회

- package.json
- src/app/(main)/animation/page.tsx
- src/app/(main)/baseball/page.tsx
- src/app/(main)/idol/page.tsx
- src/containers/goods/list/GoodsItem.tsx
- src/containers/goods/list/GoodsList.tsx
- src/containers/main/LiveAndHotItem.tsx
- src/containers/main/SoonAndHitsItem.tsx
- src/containers/main/UserDuckPoint.tsx
- src/containers/main/UserHeader.tsx
- src/containers/main/UserProfile.tsx
- src/types/goodsType.ts
- src/utils/goodsListApiActions.ts
- yarn.lock
> #68
> 무한스크롤 진행중
> 홈 화면 좋아요 기능 모달 -> callBackUrl로 수정
> 홈 화면 유저 프로필 오류 해결
> Feat: 무한 스크롤 진행중, 홈 화면 좋아요 callBackUrl로 수정

- src/app/(main)/animation/page.tsx
- src/app/(main)/baseball/page.tsx
- src/app/(main)/idol/page.tsx
- src/containers/goods/list/GoodsList.tsx
- src/containers/main/UserDuckPoint.tsx
- src/containers/main/UserHeader.tsx
- src/types/goodsType.ts
- src/utils/mainApiActions.ts
> #68 
> 무한 스크롤 isLast 수정
> 홈 화면 덕포인트 오류 해결
> 무한스크롤 코드 리팩토링 예정 ..
> Refactor: 무한 스크롤 isLast 수정, 홈 화면 덕포인트 오류 해결

- src/app/(complain)/goods-complain/page.tsx
- src/containers/complain/CheckList.tsx
- src/containers/complain/ComplainForm.tsx
- src/containers/complain/ReasonArea.tsx
- src/containers/complain/store.ts
close #94 
굿즈 신고 기능
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Feat: 굿즈 신고 기능

- src/app/(complain)/user-complain/page.tsx
- src/app/(goods)/goods/[goodsCode]/page.tsx
- src/containers/complain/CheckList.tsx
- src/containers/complain/ComplainForm.tsx
- src/containers/complain/store.ts
- src/containers/mypage/MannerDuckArea.tsx
- src/utils/etcApiActions.ts
> Feat: 유저 및 굿즈 신고 기능

- public/sw.js
- src/app/layout.tsx
- src/components/Modal/BasicAlert/index.tsx
- src/components/Modal/store.ts
- src/components/Toast/index.tsx
- src/components/Toast/store.ts
- src/containers/complain/ComplainForm.tsx
- src/containers/goods/detail/DetailHeader.tsx
- src/containers/goods/registration/GoodsForm.tsx
- src/containers/goods/registration/ImageArea.tsx
- src/containers/goods/registration/PeriodArea.tsx
- src/containers/goods/registration/TagArea.tsx
- src/containers/member/join/PhoneVerification.tsx
- src/containers/member/join/ProfileImgArea.tsx
- src/containers/member/login/LoginForm.tsx
- src/containers/mypage/update-password/ChangePasswordForm.tsx
> Feat: Toast

- src/containers/member/login/LoginForm.tsx
- src/utils/memberApiActions.ts
- src/utils/notificationApiActions.ts
> Feat: FCM 로직 수정 중

- package.json
- src/containers/member/login/LoginForm.tsx
- yarn.lock
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Feat: 디바이스토큰

- src/app/(goods)/goods/[goodsCode]/page.tsx
- src/containers/goods/detail/BiddingBtn.tsx
- src/containers/goods/detail/BiddingModal.tsx
- src/containers/goods/detail/BiddingPreview.tsx
- src/containers/goods/detail/BiddingUserItem.tsx
- src/containers/goods/detail/ConfirmModal.tsx
- src/containers/goods/detail/ConfirmationBtn.tsx
- src/containers/goods/detail/DeleteBtn.tsx
- src/containers/goods/seller/SellerMannerDuck.tsx
- src/types/goodsType.ts
- src/utils/goodsDetailApiActions.ts
> #107 
> 입찰, 낙찰 데이터 패칭
> 입찰자 리스트 패칭
> 판매자 정보 - 리뷰 패칭 수정
> soft delete 패칭
> Feat: 입찰, 낙찰, 삭제 데이터 패칭, 판매자 정보 패칭 수정

- src/components/Btn/button.tsx
- src/containers/chat/chat-room/ChatView.tsx
> close #104 
> 채팅 기능 배포시 버그 발생해서 수정하였습니다
> .
> Fix: 채팅 기능 bug 수정

- src/containers/main/LiveAndHotItem.tsx
- src/containers/main/SoonAndHitsItem.tsx
> Design: rounded 추가

- src/containers/chat/chat-list/ChatList.tsx
- src/containers/goods/list/GoodsItem.tsx
- src/types/goodsType.ts
> #68 
> 이미지 불러오는 방식 수정
> 배포 빌드 에러 해결
> GoodsItem.tsx 84번에 bg 색은 BasicImage랑 맞춘거라 저걸로 해야합니다 ~~
> Refactor: 이미지 불러오는 방식 수정

- src/components/GoodsSummary/index.tsx
- src/containers/main/ComingSoon.tsx
- src/containers/main/Hits.tsx
- src/containers/mypage/BidList.tsx
- src/types/goodsApiDataType.ts
- src/utils/goodsApiActions.ts
> #115
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> Refactor: 입찰 리스트 데이터 패칭 진행중

- src/containers/main/notification/NotificationContent.tsx
- src/containers/main/notification/NotificationModal.tsx
- src/types/notiApiDataType.ts
- src/utils/notificationApiActions.ts
> #77 
> 알림 데이터 패칭, 삭제 기능 추가
> 커밋 메시지 깜빡했습니다,,
> Feat: 알림 데이터 패칭, 삭제 기능 추가

- src/app/(chat)/chat-room/[chatRoomId]/page.tsx
- src/app/mypage/notice/[noticeId]/page.tsx
- src/app/mypage/notice/page.tsx
- src/components/Btn/TogleSwitch.tsx
- src/components/Chat/Sending.tsx
- src/containers/chat/chat-list/ChatList.tsx
- src/containers/chat/chat-room/ChatView.tsx
- src/containers/chat/chat-room/_ChatSender.tsx
- src/containers/mypage/ActivityArea.tsx
- src/containers/mypage/AnnouncementArea.tsx
- src/containers/mypage/DuckPointArea.tsx
- src/containers/mypage/InfoArea.tsx
- src/containers/mypage/MannerDuckArea.tsx
- src/containers/mypage/NoticeList.tsx
- src/containers/mypage/NotificationArea.tsx
- src/containers/mypage/TradeArea.tsx
> close #100
> 설정 페이지 구현하면서, 그 외 자잘한 버그나 콘솔로그 제거, css 수정하였습니다. 변경된 사항 아래와 같습니다
- 푸쉬 알림 및 카카오 알림 토글 스위치 구현
- 공지사항 페이지 css 수정
- 서비스이용약관 라우팅
- 개인정보처리방침 라우팅
- 마이페이지 매너덕 문구 수정 및 css 수정
- 채팅 전송상태 로딩스피너 처리 및 토스트 추가
- 채팅 css 수정
> 카카오 알림 및 푸쉬 알림 토글 스위치에 따라 상태(true,false)받아오는건 해두었는데, 그에 따라 api 요청하는건
안해두었습니다. 추후 연결해야합니다.
> 채팅에 이미지 보내고, 받는 로직 도움이 필요합니다
> 공지사항 페이지에 이미지도 나올수있게 해야하는데 도움이 필요합니다
> Feat: 설정 페이지 구현

- src/containers/goods/detail/DetailDescription.tsx
- src/containers/goods/registration/TagArea.tsx
- src/containers/main/TagItem.tsx
> Refactor: 태그 정적으로 변경

- src/containers/goods/list/GoodsItem.tsx
- src/containers/goods/list/GoodsList.tsx
- src/containers/main/search/SearchForm.tsx
- src/containers/main/search/SearchModal.tsx
- src/utils/goodsListApiActions.ts
> #77
> 검색 화면 css 수정, 검색하면 연관 검색어 사라지도록 수정
> 굿즈 아이템 css 수정
> Refactor: 검색 화면 수정, 굿즈 아이템 수정

- src/app/manifest.ts
- src/containers/chat/chat-room/ChatViewReceiverCard.tsx
- src/containers/chat/chat-room/ChatViewSenderCard.tsx
- src/containers/chat/chat-room/_ChatSender.tsx
> .
> chat 관련 css 수정하고, 배포를 위해 manifest파일 수정하였습니다
> .
> Feat: manifest.ts 수정 외

- src/app/(goods)/goods/[goodsCode]/page.tsx
- src/components/layout/RegistrationBtn.tsx
- src/components/layout/UpNav.tsx
- src/containers/category/Category.tsx
- src/containers/goods/detail/DetailInfo.tsx
- src/containers/goods/list/GoodsItem.tsx
- src/containers/goods/registration/GoodsForm.tsx
- src/containers/goods/registration/TagArea.tsx
- src/containers/main/Hits.tsx
- src/containers/main/HotInterest.tsx
- src/containers/main/LiveAndHotItem.tsx
- src/containers/main/LiveBidding.tsx
- src/containers/main/MainCategory.tsx
- src/containers/main/SoonAndHitsItem.tsx
- src/types/mainType.ts
> #132 
> 상품 등록, 좋아요 에러 방지 / 홈 css 수정
> Refactor: 상품 등록, 좋아요 에러 방지 / 홈 css 수정

- src/app/(chat)/chat-room/[chatRoomId]/page.tsx
- src/components/Chat/ConfirmModal.tsx
- src/components/Chat/NickName.tsx
- src/containers/chat/chat-list/ChatList.tsx
- src/containers/chat/chat-list/ChatRoomImage.tsx
- src/containers/chat/chat-list/LastChat.tsx
- src/containers/chat/chat-room/ChatView.tsx
- src/containers/chat/chat-room/GoToReviewBtn.tsx
- src/containers/chat/chat-room/_ChatSender.tsx
- src/containers/mypage/bid/BidContent.tsx
- src/containers/mypage/winning-bid/WinningContent.tsx
> close #136 
> 채팅방 및 채팅룸 상품정보 불러오기
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> Feat: 채팅방 및 채팅룸 상품정보 불러오기

- public/sw.js
- src/containers/mypage/review/ReviewItem.tsx
- src/containers/mypage/review/ReviewModal.tsx
- src/containers/review/ReviewForm.tsx
- src/utils/etcApiActions.ts
> Fix: 데이터 패칭 오류 해결

- src/components/Btn/LikeBtn.tsx
- src/containers/goods/detail/BiddingUserItem.tsx
- src/containers/goods/detail/DetailInfo.tsx
- src/containers/goods/list/GoodsItem.tsx
- src/containers/main/LiveAndHotItem.tsx
- src/containers/main/SoonAndHitsItem.tsx
- src/containers/mypage/review/ReviewItem.tsx
- src/containers/review/ReviewForm.tsx
> Refactor: 좋아요 수정, 기본이미지 s3 적용

- package.json
- src/components/layout/SubHeader.tsx
- src/containers/category/Category.tsx
- src/containers/chat/chat-list/ChatListTopSection.tsx
- src/containers/chat/chat-room/ChatView.tsx
- src/containers/goods/list/GoodsItem.tsx
- src/containers/main/AdvertisingBanner.tsx
- src/containers/main/HotInterest.tsx
- src/containers/main/LiveBidding.tsx
- src/containers/main/MainCategory.tsx
- src/containers/main/SoonAndHitsItem.tsx
- src/containers/mypage/ActivityArea.tsx
- src/containers/mypage/DuckPointArea.tsx
- src/containers/mypage/InfoArea.tsx
- src/containers/mypage/MannerDuckArea.tsx
- src/containers/mypage/TradeArea.tsx
- src/containers/mypage/like/LikeItem.tsx
- yarn.lock
> Feat: css transition 추가
